on: [ push, pull_request ]
name: tests
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dart action
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      #          sdk: '2.13.0'
      - name: Install dependencies
        run: dart pub get
      - name: Run tests & test coverage
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v2
        with:
          file: coverage/lcov.info